server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GaoYanTai/aispringcloud.git
          search-paths: config
          username: 2864182062@qq.com
          password: gyt201932168
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/